### ISSUE TITLE
Create ingame map / prefab editor

### ISSUE THREAD

**Issue by rm-code** [rm-code/On-The-Roadside#199]
After playing around with tons of different editors and file formats I think the best way to add new map content to the game is to write an ingame editor.

- First of all there would be no need for any conversion between external formats and the ones used by OTR (plus any mapping to actual content).
- With a custom map editor we can directly load all tile and worldobject templates we have in the game and use them to create new content.
- We can also easily add special information (like road alignment #186)
- It would also be easily accessible by players and modders later on

## TODOs

- [x] Screen with grid and camera
- [x] Draw Mode
- [x] Fill Mode
- [x] Erase Mode
- [x] Different cursor sizes
- [x] Different canvas sizes
- [x] Hide object layer on keypress
- [x] Highlight layer if type is selected (make other translucent?)
- [x] Tab between select lists
- [x] Layout grid resizable
- [x] Show cursor mode, selected brush, brush size, grid size on UI
- [x] Custom names
- [x] File loading screen ... scrollable

## TODOs Refactor

- [x] PrefabCanvas

## FIXME

- [x] EditorLoadingScreen has still normal input
